parameters:
    doctrine_behaviors_translatable_fetch_mode: "LAZY"
    doctrine_behaviors_translation_fetch_mode: "LAZY"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $faker: '@faker'
            $ruFaker: '@ruFaker'
            $env: '%env(APP_ENV)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    faker:
        class: Faker\Generator
        factory: ['Faker\Factory', 'create']

    ruFaker:
        class: Faker\Generator
        factory: ['Faker\Factory', 'create']
        arguments: ['ru_RU']
